/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author renat
 */
public class solo extends javax.swing.JFrame {

    /**
     * Creates new form solo
     */
    public solo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sair = new javax.swing.JButton();
        Ysolo = new javax.swing.JLabel();
        xSolo = new javax.swing.JTextField();
        ySolo = new javax.swing.JTextField();
        solo = new javax.swing.JLabel();
        Xsolo = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        LabelFresnell = new javax.swing.JLabel();
        sair1 = new javax.swing.JButton();
        adicionarPonto = new javax.swing.JButton();

        sair.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ysolo.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        Ysolo.setText("Coordenada Y:");

        solo.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        solo.setText("Solo");

        Xsolo.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        Xsolo.setText("Coordenada X:");

        calcular.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        calcular.setText("Calcular");

        LabelFresnell.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        LabelFresnell.setText("Zona de Fresnel");

        sair1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        sair1.setText("Sair");
        sair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair1ActionPerformed(evt);
            }
        });

        adicionarPonto.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        adicionarPonto.setText("Adicionar ponto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(LabelFresnell)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(adicionarPonto)
                        .addGap(18, 18, 18)
                        .addComponent(calcular)
                        .addGap(18, 18, 18)
                        .addComponent(sair1)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(solo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Xsolo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Ysolo, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(xSolo)
                                    .addComponent(ySolo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(211, 211, 211))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(LabelFresnell)
                .addGap(48, 48, 48)
                .addComponent(solo)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Xsolo)
                    .addComponent(xSolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ysolo)
                    .addComponent(ySolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcular)
                    .addComponent(sair1)
                    .addComponent(adicionarPonto))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void sair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sair1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFresnell;
    private javax.swing.JLabel Xsolo;
    private javax.swing.JLabel Ysolo;
    private javax.swing.JButton adicionarPonto;
    private javax.swing.JButton calcular;
    private javax.swing.JButton sair;
    private javax.swing.JButton sair1;
    private javax.swing.JLabel solo;
    private javax.swing.JTextField xSolo;
    private javax.swing.JTextField ySolo;
    // End of variables declaration//GEN-END:variables
}
